nelmio_api_doc:
    documentation:
        info:
            title: Animals Rest Api
            description: This is a Rest Api
            version: 1.0.0
        paths:
            '/animals':
                get:
                    description: Returns all animals from the system that the user has access to
                    responses:
                        '200':
                            description: A list of animals.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }
            '/animal':
                post:
                    description: Add an animal to database
                    responses:
                        '200':
                            description: A confirmation of the animal's add.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }
            '/animal/{id}':
                get:
                    description: Add an animal to database
                    responses:
                        '200':
                            description: A confirmation of the animal's add.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }
                put:
                    description: Update an animal
                    responses:
                        '200':
                            description: A confirmation of the animal's update.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }
                patch:
                    description: Update an animal's country
                    responses:
                        '200':
                            description: A confirmation of the animal's update.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }
                delete:
                    description: Delete an animal by his id
                    responses:
                        '200':
                            description: A confirmation of the animal deletion.
                            content:
                                application/json:
                                    type: object
                                    properties: { }
            '/animals/{country}':
                get:
                    description: Returns all animals from an country id
                    responses:
                        '200':
                            description: A list of animals.
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties: { }

    areas: # to filter documented areas
        path_patterns:
            #- ^/
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
