getAnimalById:
    path: /api/animal/{id}
    controller: App\Controller\AnimalsController::getAnimalById
    methods:    GET
listAllAnimalsByCountry:
    path: /api/animals/{country}
    controller: App\Controller\AnimalsController::listAllAnimalsByCountry
    methods:    GET
updateAnimal:
    path: /api/animal/{id}
    controller: App\Controller\AnimalsController::updateAnimal
    methods:    PUT
updateAnimalCountry:
    path: /api/animal/{id}
    controller: App\Controller\AnimalsController::updateAnimalCountry
    methods:    PATCH
deleteAnimalById:
    path: /api/animal/{id}
    controller: App\Controller\AnimalsController::deleteAnimalById
    methods:    DELETE
listAllAnimals:
    path: /api/animals
    controller: App\Controller\AnimalsController::listAllAnimals
    methods: GET
AddAnimal:
    path: /api/animal
    controller: App\Controller\AnimalsController::AddAnimal
    methods:    POST
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute